version: '3'

services:
  app:
    build: .
    container_name: qmobi
    environment:
      - PORT=${PORT}
      - HOST_NAME=${HOST_NAME}
      - CURRENCIES_API_KEY=${CURRENCIES_API_KEY}
    ports:
      - ${PORT}:${PORT}
    restart: always